name: "Dep Job Example" 

on: ['push']

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: stepB
        run: echo "world"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: stepA
        run: echo "hello"
  